site_name: AI Learning Hub
theme:
  name: material

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Python Basics:
      - Introduction: python/intro.ipynb
      - Variables: python/variables.ipynb
  - Math for AI:
      - Linear Algebra: math/linear-algebra.ipynb