site_name: AI Learning Hub
theme:
  name: material

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Phase 0 - Programming Foundations:
      - Introduction: python/intro.ipynb
  - Phase 1 - Core Python:
      - Introduction: python/core-python/python-syntax.ipynb
  - Phase 2 - Intermediate Python:
      - Introduction: python/intro.ipynb
  - Phase 3 - Python for Data Handling:
      - Introduction: python/intro.ipynb
  - Phase 4 - Mathematics for AI:
      - Introduction: python/intro.ipynb
  - Phase 5 - Machine Learning:
      - Introduction: python/intro.ipynb
  - Phase 6 - Deep Learning:
      - Introduction: python/intro.ipynb
  - Phase 7 - Specialized AI Domains:
      - Introduction: python/intro.ipynb
  - Phase 8 - Advanced Python & MLOps:
      - Introduction: python/intro.ipynb
  - Projects:
      - Introduction: python/intro.ipynb